SIP 0010: Staking at cliff == duration fix
DistributedCollective/SIPS pull request #9
Opened 2021-03-01 15:55 UTC by tjcloa

2021-03-01 19:54 UTC, exiledsurfer commented
My suggestion for the SIP-010 text:

**Background:**
The currently deployed staking contract’s stakeByschedule function used by the currently deployed vesting contracts only allow for staking for two six-week intervals, which means that SOV tokens from the Origin resale can not be distributed with deploying one single contract. The currently deployed staking contract would require to release 50% at one date, and the second 50% four weeks later. This would be unfair to Origin resale bidders. 

Therefore, It is proposed that voting on SIP-010 begin on Tuesday, March 2nd and close 24 hours later on Wednesday March 3rd, 2021.

Approval of SIP-010 would result in the disbursal of Origin SOV presale tokens taking place 48 hours after the conclusion of a successful vote, on Friday March 5th, which would allow for rigorous testing on testnet before deploying to mainnet. 

**Resolved:**
In order to distribute 100% of Origin SOV in one transaction, it is proposed to change the staking contract https://github.com/DistributedCollective/Sovryn-smart-contracts/blob/development/contracts/governance/Staking/Staking.sol#L182 from "a <" to "a <="

2021-03-01 19:59 UTC, exiledsurfer commented
additional comment: i discussed this text proposal with @ororopickpocket who maintained that the voting schedule and the disbursal schedule timings should not appear in the text, with which i respectfully disagree, on the grounds that clarity is called for in messaging, and having that timeline of what will happen when after what puts us in a better position to point to the vote as the determinative factor in when origins presale bidders will receive their tokens. 

Although we've done a good job keeping them patient in channels, our last line of comms since last friday has been that disbursal would be taking place by tuesday. 

It will be a far easier "sell" to say, 

"hey folks, the sale price vote passed, yay, now the disbursal has to be voted on as a normal process, and we've made it more fair by taking the time to adjust our staking contract to be more flexible and more fair."

2021-03-01 21:05 UTC, john-light requested changes
Updated SIP with new language

2021-03-01 21:05 UTC, john-light commented on SIP-0010.md
> +The fix covers the edge case when we need to stake with cliff equal to duration (period)
```suggestion

## Background
The current Staking contract’s `stakeByschedule` function, used by the current vesting contracts, only allows staking for a minimum of two four-week intervals. Additionally, the current Staking contract cannot be used with a Vesting contract.

## Resolved
- The change implemented in [this pull request](https://github.com/DistributedCollective/Sovryn-smart-contracts/pull/158) at [this commit](https://github.com/DistributedCollective/Sovryn-smart-contracts/pull/158/commits/958e4d86c523468fd239d4dc2b533174154e8af9) will be implemented to a) allow staking for a minimum of one interval, and b) allow us to use a Vesting contract with the Staking contract.

2021-03-01 21:19 UTC, exiledsurfer commented on SIP-0010.md
> +The fix covers the edge case when we need to stake with cliff equal to duration (period)
yeah, i understand your changes, but when i discussed with @ororopickpocket initially, i asked if the sip would be posted to the forum, and she said "no, it shouldnt need any discussion". My preference is that it IS posted to the forum, and explains more deeply why we're doing what we're doing, which includes a "sequence of events" that will transpire when the sip is passed. i had originally included actual times voting would start and end in the sip draft i shared with ororo, and she pointed out that times could change, so i eliminated the times but kept the dates. According to ororo, the distribution would happen 72 hours after the SIP was deployed, which is how i came to the 48 hours / friday date.

2021-03-01 21:23 UTC, exiledsurfer commented on SIP-0010.md
> +The fix covers the edge case when we need to stake with cliff equal to duration (period)
@john-light i do believe that for purposes of transparency, as well as for ease of communicating this unexpected change to users expecting to get their tokens tomorrow, that we at least have a link to a forum post to use on SM channels (discord, tellygrammy, discord).

2021-03-01 23:57 UTC, john-light commented on SIP-0010.md
> +The fix covers the edge case when we need to stake with cliff equal to duration (period)
> Would be great if you could do such a forum post - i don't think a blog post would be necessary.

It's not my SIP and I'm not involved at all with the token logistics so I'm not the best person to post in the forum or answer questions about this. Someone who knows those details and how they relate to this SIP would be better to post it.

2021-03-02 02:35 UTC, ororopickpocket commented on SIP-0010.md
> +The fix covers the edge case when we need to stake with cliff equal to duration (period)
i could not commit this suggestion directly, because tyrone pushed a commit in the meantime, which made above suggestion 'outdated'. therefore i commited it in bf08017 with minor changes.

2021-03-02 02:36 UTC, ororopickpocket approved these changes

2021-03-02 12:14 UTC, merged